-- V1 — initial schema for the Document Control system.
-- Mirrors Document_Control_Data_Model_v1.md exactly, plus the four resolved
-- schema decisions from CLAUDE.md ("Schema decisions"):
--   * user_role join table (many-to-many user <-> role)
--   * user.password_hash (bcrypt; nullable so future AD/LDAP accounts can leave it unused)
--   * document.deleted_at (soft delete; lifecycle status stays a separate concern)
--   * audit_log.details as jsonb
-- Enum-like columns are text with CHECK constraints (values exactly as listed in
-- the data model doc) — extensible via migration, no native PG enum types.

-- ============================================================
-- 1. Lookup tables (extensible — no hardcoded types)
-- ============================================================

CREATE TABLE document_tier (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_number integer NOT NULL,
    label       text    NOT NULL,
    active      boolean NOT NULL DEFAULT true
);

CREATE TABLE document_type (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    text    NOT NULL UNIQUE,
    label   text    NOT NULL,
    tier_id integer NOT NULL REFERENCES document_tier (id),
    active  boolean NOT NULL DEFAULT true
);

CREATE TABLE department (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   text    NOT NULL UNIQUE,
    label  text    NOT NULL,
    active boolean NOT NULL DEFAULT true
);

-- One row per (type, department) pair; the single source of truth for the next
-- document number. Rows are created lazily when the first document of a pair
-- is created. Gaps in the sequence are expected and fine (see CLAUDE.md).
CREATE TABLE document_sequence_counter (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id     integer NOT NULL REFERENCES document_type (id),
    department_id        integer NOT NULL REFERENCES department (id),
    next_sequence_number integer NOT NULL,
    CONSTRAINT uq_sequence_counter_type_department UNIQUE (document_type_id, department_id)
);

-- ============================================================
-- 4. Identity (created before core document tables, which reference it)
-- ============================================================

-- "user" is a reserved word in PostgreSQL — always quoted, here and in the
-- JPA mapping (@Table(name = "\"user\"")).
CREATE TABLE "user" (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text    NOT NULL,
    email         text    NOT NULL UNIQUE,
    department_id integer NOT NULL REFERENCES department (id),
    ad_username   text,
    password_hash text,   -- bcrypt; unused for future AD/LDAP-sourced accounts
    active        boolean NOT NULL DEFAULT true
);

CREATE TABLE role (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text    NOT NULL UNIQUE
);

CREATE TABLE user_role (
    user_id integer NOT NULL REFERENCES "user" (id),
    role_id integer NOT NULL REFERENCES role (id),
    PRIMARY KEY (user_id, role_id)
);

-- ============================================================
-- 2. Core document entities
-- ============================================================

CREATE TABLE document (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number    text    NOT NULL UNIQUE,
    document_type_id   integer NOT NULL REFERENCES document_type (id),
    department_id      integer NOT NULL REFERENCES department (id),
    sequence_number    integer NOT NULL,
    name               text    NOT NULL,
    status             text    NOT NULL,
    current_version_id integer,
    owner_user_id      integer NOT NULL REFERENCES "user" (id),
    created_at         timestamp NOT NULL DEFAULT now(),
    updated_at         timestamp NOT NULL DEFAULT now(),
    deleted_at         timestamp,
    CONSTRAINT ck_document_status
        CHECK (status IN ('draft', 'in_review', 'approved', 'released', 'superseded', 'obsolete'))
);

CREATE TABLE document_version (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id           integer NOT NULL REFERENCES document (id),
    version_number        integer NOT NULL,
    file_reference        text    NOT NULL,
    legacy_revision_label text,
    status                text    NOT NULL,
    change_notes          text,
    uploaded_by           integer NOT NULL REFERENCES "user" (id),
    uploaded_at           timestamp NOT NULL DEFAULT now(),
    CONSTRAINT ck_document_version_status
        CHECK (status IN ('draft', 'current', 'superseded'))
);

-- One version number per document, system-assigned (never in the filename).
ALTER TABLE document_version
    ADD CONSTRAINT uq_document_version_number UNIQUE (document_id, version_number);

-- Circular FK between document and document_version: the current-version FK is
-- added after document_version exists, and stays nullable (a brand-new document
-- has no version until one is uploaded).
ALTER TABLE document
    ADD CONSTRAINT fk_document_current_version
    FOREIGN KEY (current_version_id) REFERENCES document_version (id);

-- ============================================================
-- 3. Workflow (stage-based, flexible from the start)
--    Schema exists from Sprint 1 so the model never needs a rewrite; the
--    endpoints themselves are Sprint 3 (see API spec).
-- ============================================================

CREATE TABLE workflow_template (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text    NOT NULL,
    document_type_id integer REFERENCES document_type (id),   -- null = any type
    department_id    integer REFERENCES department (id),      -- null = any department
    active           boolean NOT NULL DEFAULT true
);

CREATE TABLE workflow_stage (
    id                           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id                  integer NOT NULL REFERENCES workflow_template (id),
    stage_order                  integer NOT NULL,
    name                         text    NOT NULL,
    approval_mode                text    NOT NULL,
    required_approval_percentage integer NOT NULL DEFAULT 100,
    due_date_offset_days         integer,
    CONSTRAINT ck_workflow_stage_approval_mode
        CHECK (approval_mode IN ('parallel', 'single'))
);

CREATE TABLE workflow_stage_assignee (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id integer NOT NULL REFERENCES workflow_stage (id),
    user_id  integer REFERENCES "user" (id),   -- specific person...
    role_id  integer REFERENCES role (id)      -- ...or assign by role instead
);

CREATE TABLE workflow_instance (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id integer NOT NULL REFERENCES document_version (id),
    template_id         integer NOT NULL REFERENCES workflow_template (id),
    current_stage_id    integer REFERENCES workflow_stage (id),
    status              text    NOT NULL,
    started_by          integer NOT NULL REFERENCES "user" (id),
    started_at          timestamp NOT NULL DEFAULT now(),
    completed_at        timestamp,
    CONSTRAINT ck_workflow_instance_status
        CHECK (status IN ('in_progress', 'completed', 'rejected'))
);

CREATE TABLE workflow_task (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id         integer NOT NULL REFERENCES workflow_instance (id),
    stage_id            integer NOT NULL REFERENCES workflow_stage (id),
    assigned_to_user_id integer NOT NULL REFERENCES "user" (id),
    outcome             text    NOT NULL,
    comment             text,
    completed_at        timestamp,
    CONSTRAINT ck_workflow_task_outcome
        CHECK (outcome IN ('pending', 'approved', 'rejected'))
);

-- ============================================================
-- 4. Audit
-- ============================================================

CREATE TABLE audit_log (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type  text    NOT NULL,
    entity_id    integer NOT NULL,
    action       text    NOT NULL,
    performed_by integer NOT NULL REFERENCES "user" (id),
    performed_at timestamp NOT NULL DEFAULT now(),
    details      jsonb
);
