-- V4 — Phase 2b: Flowable 8 owns workflow runtime state (tasks, assignees,
-- candidate groups, history in its ACT_* tables). Our schema keeps the thin
-- workflow_instance link (document version <-> engine process) and a
-- notification log; the Sprint-1 template/stage/task tables are superseded
-- by engine state and are dropped per the approved Phase 2b design.

ALTER TABLE workflow_instance DROP COLUMN template_id;
ALTER TABLE workflow_instance DROP COLUMN current_stage_id;
ALTER TABLE workflow_instance ADD COLUMN process_instance_id text;

CREATE TABLE notification_log (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                 text    NOT NULL,   -- REMINDER / ESCALATION
    workflow_instance_id integer NOT NULL REFERENCES workflow_instance (id),
    flowable_task_id     text,
    recipient            integer NOT NULL REFERENCES "user" (id),
    subject              text,
    sent_at              timestamp NOT NULL DEFAULT now(),
    channel              text    NOT NULL    -- 'log' until Graph lands
);

DROP TABLE workflow_task;
DROP TABLE workflow_stage_assignee;
DROP TABLE workflow_stage;
DROP TABLE workflow_template;
