-- V7 — Phase 2d: read & understood acknowledgment. Record-only audit
-- evidence (nothing is gated on it). Designed in
-- Phase2c_2d_Design_PlanBack.md:
--   * document_acknowledgment — one row per (version, user); the unique
--     constraint IS the no-carry-forward rule: every newly-effective
--     version re-opens acknowledgment for the whole department.
--   * document_acknowledgment_access — per-document, per-user grants for
--     viewing a document's acknowledgment status (owner/admin by default);
--     grants status visibility only, no document permissions.

CREATE TABLE document_acknowledgment (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id integer NOT NULL REFERENCES document_version (id),
    user_id             integer NOT NULL REFERENCES "user" (id),
    acknowledged_at     timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_acknowledgment UNIQUE (document_version_id, user_id)
);

CREATE TABLE document_acknowledgment_access (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL REFERENCES document (id),
    user_id     integer NOT NULL REFERENCES "user" (id),
    granted_by  integer NOT NULL REFERENCES "user" (id),
    granted_at  timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_acknowledgment_access UNIQUE (document_id, user_id)
);
